export const lotto3dGameAbi = [
  { "type": "constructor", "inputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "ADMIN_ROLE", "inputs": [], "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }], "stateMutability": "view" },
  { "type": "function", "name": "DEFAULT_ADMIN_ROLE", "inputs": [], "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }], "stateMutability": "view" },
  { "type": "function", "name": "KEEPER_ROLE", "inputs": [], "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }], "stateMutability": "view" },
  { "type": "function", "name": "MAX_BATCH_SIZE", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "MAX_TICKETS_PER_ADDRESS", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "PRIZE1_BPS", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "PRIZE2_BPS", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "PRIZE3_BPS", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "VRF_ROLE", "inputs": [], "outputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }], "stateMutability": "view" },
  { "type": "function", "name": "cancelRound", "inputs": [{ "name": "roundId", "type": "uint40", "internalType": "uint40" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "closeSales", "inputs": [{ "name": "roundId", "type": "uint40", "internalType": "uint40" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "createRound", "inputs": [{ "name": "roundId", "type": "uint40", "internalType": "uint40" }, { "name": "config", "type": "tuple", "internalType": "struct ILotto3DGame.RoundConfig", "components": [{ "name": "salesOpenTime", "type": "uint64", "internalType": "uint64" }, { "name": "salesCloseTime", "type": "uint64", "internalType": "uint64" }, { "name": "drawDeadline", "type": "uint64", "internalType": "uint64" }] }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "getRound", "inputs": [{ "name": "roundId", "type": "uint40", "internalType": "uint40" }], "outputs": [{ "name": "", "type": "tuple", "internalType": "struct ILotto3DGame.RoundData", "components": [{ "name": "exists", "type": "bool", "internalType": "bool" }, { "name": "status", "type": "uint8", "internalType": "enum ILotto3DGame.RoundStatus" }, { "name": "config", "type": "tuple", "internalType": "struct ILotto3DGame.RoundConfig", "components": [{ "name": "salesOpenTime", "type": "uint64", "internalType": "uint64" }, { "name": "salesCloseTime", "type": "uint64", "internalType": "uint64" }, { "name": "drawDeadline", "type": "uint64", "internalType": "uint64" }] }, { "name": "totalSales", "type": "uint256", "internalType": "uint256" }, { "name": "totalTickets", "type": "uint256", "internalType": "uint256" }, { "name": "winningNumber", "type": "uint16", "internalType": "uint16" }, { "name": "prizePool", "type": "uint256", "internalType": "uint256" }, { "name": "prize1PerUnit", "type": "uint256", "internalType": "uint256" }, { "name": "prize2PerUnit", "type": "uint256", "internalType": "uint256" }, { "name": "prize3PerUnit", "type": "uint256", "internalType": "uint256" }, { "name": "winUnits1", "type": "uint256", "internalType": "uint256" }, { "name": "winUnits2", "type": "uint256", "internalType": "uint256" }, { "name": "winUnits3", "type": "uint256", "internalType": "uint256" }] }], "stateMutability": "view" },
  { "type": "function", "name": "isRoundSettled", "inputs": [{ "name": "roundId", "type": "uint40", "internalType": "uint40" }], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "latestRoundId", "inputs": [], "outputs": [{ "name": "", "type": "uint40", "internalType": "uint40" }], "stateMutability": "view" },
  { "type": "function", "name": "ledger", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "contract IUnifiedLedgerV4" }], "stateMutability": "view" },
  { "type": "function", "name": "paused", "inputs": [], "outputs": [{ "name": "", "type": "bool", "internalType": "bool" }], "stateMutability": "view" },
  { "type": "function", "name": "previousRoundId", "inputs": [{ "name": "roundId", "type": "uint40", "internalType": "uint40" }], "outputs": [{ "name": "previous", "type": "uint40", "internalType": "uint40" }], "stateMutability": "view" },
  { "type": "function", "name": "purchaseFromLedgerV4", "inputs": [{ "name": "payer", "type": "address", "internalType": "address" }, { "name": "beneficiary", "type": "address", "internalType": "address" }, { "name": "amount", "type": "uint256", "internalType": "uint256" }, { "name": "context", "type": "tuple", "internalType": "struct IGameModuleV4.PurchaseContext", "components": [{ "name": "wfOrderId", "type": "bytes32", "internalType": "bytes32" }, { "name": "partnerCode", "type": "bytes32", "internalType": "bytes32" }] }, { "name": "purchaseData", "type": "bytes", "internalType": "bytes" }], "outputs": [{ "name": "receiptId", "type": "bytes32", "internalType": "bytes32" }, { "name": "allocationVersion", "type": "uint32", "internalType": "uint32" }, { "name": "partnerBps", "type": "uint16", "internalType": "uint16" }], "stateMutability": "nonpayable" },
  { "type": "function", "name": "ticketPrice", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "ticketsPerAddress", "inputs": [{ "name": "roundId", "type": "uint40", "internalType": "uint40" }, { "name": "user", "type": "address", "internalType": "address" }], "outputs": [{ "name": "count", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "treasury", "inputs": [], "outputs": [{ "name": "", "type": "address", "internalType": "contract IWusdLotto3DTreasury" }], "stateMutability": "view" },
  { "type": "error", "name": "RoundNotOpen", "inputs": [] },
  { "type": "error", "name": "SalesNotClosed", "inputs": [] },
  { "type": "error", "name": "BatchTooLarge", "inputs": [] },
  { "type": "error", "name": "InvalidNumber", "inputs": [] },
  { "type": "error", "name": "PurchaseAmountMismatch", "inputs": [] },
  { "type": "error", "name": "RoundAlreadyCancelled", "inputs": [] },
  { "type": "error", "name": "RoundAlreadySettled", "inputs": [] },
  { "type": "error", "name": "MaxTicketsReached", "inputs": [] },
  { "type": "error", "name": "PreviousRoundUnresolved", "inputs": [{ "name": "previousRoundId", "type": "uint40", "internalType": "uint40" }] },
  { "type": "error", "name": "PrizeClaimExpired", "inputs": [{ "name": "roundId", "type": "uint40", "internalType": "uint40" }] },
  { "type": "error", "name": "UnsupportedBeneficiary", "inputs": [] },
  { "type": "error", "name": "InvalidRoundOrder", "inputs": [] },
  { "type": "error", "name": "InvalidConfig", "inputs": [] },
  { "type": "error", "name": "RoundNotCancelled", "inputs": [] },
  { "type": "error", "name": "RoundNotSettled", "inputs": [] },
  { "type": "error", "name": "AlreadyClaimed", "inputs": [] },
  { "type": "error", "name": "AlreadyRefunded", "inputs": [] },
  { "type": "error", "name": "NoPrize", "inputs": [] },
  { "type": "error", "name": "ClaimPeriodOutOfRange", "inputs": [] },
  { "type": "error", "name": "OnlyLedger", "inputs": [] },
  { "type": "error", "name": "EnforcedPause", "inputs": [] }
] as const;
